config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'
  get 'home/index', to: 'home#index'

  namespace :user do
    get 'profile', to: 'profiles#show'
    get 'profile/edit', to: 'profiles#edit'
    put 'profile', to: 'profiles#update'
  end

  devise_scope :user do
    get :users, to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :clubs
  resources :rounds
  resources :players
  resources :tournaments do
    resources :matches do
      member do
        post :add_goal # should be MatchGoal nested resource?
      end
    end
    resources :teams do
      collection do
        get :register
        post :create_from_register
      end

      member do
        get :registration_done
      end
    end
  end
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  include CountryNameable

  GENDERS = %w[
    female
    male
    other
  ].freeze

  enum(:gender, GENDERS.to_h { |h| [h, h] })

  SHIRT_SIZES = %w[
    XXS
    XS
    S
    M
    L
    XL
    XXL
    XXXL
  ].freeze

  delegate :name, to: :club, prefix: true, allow_nil: true

  belongs_to :club, optional: true
  belongs_to :user, optional: true
  has_one :player, inverse_of: :profile, dependent: :destroy
  # TODO: should validate a profile can't be deleted if players are associated to tournaments

  has_many :identification_documents, inverse_of: :profile, dependent: :destroy

  validates :first_name, presence: true

  def name
    [
      first_name,
      middle_name,
      last_name,
      second_last_name
    ].join(' ')
  end

  def display_name
    first_name || nickname
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  OMNIAUTH_PROVIDERS = %i[google_oauth2 facebook].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable,
         :omniauthable, omniauth_providers: OMNIAUTH_PROVIDERS

  has_one :profile
  delegate :preferred_locale, to: :profile, allow_nil: true

  def display_name
    profile&.display_name || email
  end

  def first_and_last_name
    return email unless profile

    name = "#{profile.first_name} #{profile.last_name}".squish

    return email if name.blank?

    name
  end

  # TODO: create a separate method or each provider
  def self.from_omniauth(access_token)
    data = access_token.info
    # rubocop: disable Style/RedundantAssignment
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # if user.blank?

    #   user = User.create( # name: data['name'],
    #     email: data['email'],
    #     password: Devise.friendly_token[0,20]
    #   )
    # end
    user
    # rubocop: enable Style/RedundantAssignment
  end

  protected

  def send_devise_notification(notification, *args)
    if Rails.env.development?
      devise_mailer.send(notification, self, *args).deliver_now
      return
    end

    devise_mailer.send(notification, self, *args).deliver_later(queue: 'mailers')
  end
end

app/controllers/user/profiles_controller.rb
# frozen_string_literal: true

class User::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_profile

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to user_profile_url, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_profile
    @user_profile = current_user.profile || current_user.build_profile
  end

  # Only allow a list of trusted parameters through.
  def user_profile_params
    params.require(:profile).permit(
      :first_name,
      :middle_name,
      :last_name,
      :second_last_name,
      :nickname,
      :dob,
      :country_code,
      :city,
      :club_id,
      :shirt_size,
      :lefty,
      :gender,
      :other_gender,
      :pronouns,
      :food_preferences,
      :allergies,
      :preferred_locale
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def google_oauth2
    # debugger
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    # debugger
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/user/profiles_helper.rb
# frozen_string_literal: true

module User::ProfilesHelper
end

app/views/user/profiles/_form.html.slim
= simple_form_for([current_user , @user_profile], url: user_profile_url, method: :put) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name
    = f.input :second_last_name
    = f.input :nickname
    = f.input :dob, start_year: Date.today.year - 110, end_year: Date.today.year, order: [:day, :month, :year]
    = f.input :country_code
    = f.input :city
    = f.input :club_id
    = f.input :shirt_size, collection: Profile::SHIRT_SIZES, prompt: t('select')
    = f.input :lefty
    = f.input :gender, collection: Profile::GENDERS.to_h { |h| [t(h), h] }, prompt: t('select')
    = f.input :other_gender
    = f.input :pronouns
    = f.input :food_preferences
    = f.input :allergies
    = f.input :preferred_locale, collection: I18n.available_locales.to_h { |l| [t("languages.#{l}"), l] }

  .form-actions
    = f.button :submit

app/views/user/profiles/_profile.html.slim
div id="#{dom_id profile}"
  p
    strong
      = Profile.human_attribute_name(:first_name)
      |:
    =< profile.first_name
  p
    strong
      = Profile.human_attribute_name(:middle_name)
      |:
    =< profile.middle_name
  p
    strong
      = Profile.human_attribute_name(:last_name)
      |:
    =< profile.last_name
  p
    strong
      = Profile.human_attribute_name(:second_last_name)
      |:
    =< profile.second_last_name
  p
    strong
      = Profile.human_attribute_name(:nickname)
      |:
    =< profile.nickname
  p
    strong
      = Profile.human_attribute_name(:dob)
      |:
    =< profile.dob? ? l(profile.dob, format: :long) : nil
  p
    strong
      = Profile.human_attribute_name(:country_code)
      |:
    =< profile.country_flag
    =< profile.country_name
    |  (
    = profile.country_code
    |)
  p
    strong
      = Profile.human_attribute_name(:city)
      |:
    =< profile.city
  p
    strong
      = Profile.human_attribute_name(:club_id)
      |:
    =< profile.club_name
  p
    strong
      = Profile.human_attribute_name(:shirt_size)
      |:
    =< profile.shirt_size
  p
    strong
      = Profile.human_attribute_name(:lefty)
      |:
    =< !profile.lefty ? t('yes') : t('no')
  p
    strong
      = Profile.human_attribute_name(:gender)
      |:
    =< t(profile.gender)
  p
    strong
      = Profile.human_attribute_name(:other_gender)
      |:
    =< profile.other_gender
  p
    strong
      = Profile.human_attribute_name(:pronouns)
      |:
    =< profile.pronouns
  p
    strong
      = Profile.human_attribute_name(:food_preferences)
      |:
    =< profile.food_preferences
  p
    strong
      = Profile.human_attribute_name(:allergies)
      |:
    =< profile.allergies
  p
    strong
      = Profile.human_attribute_name(:preferred_locale)
      |:
    =< t("languages.#{profile.preferred_locale}")

app/views/user/profiles/edit.html.slim
h1.font-bold.text-4xl
  = t('editing')
  =< Profile.model_name.human

== render "form", user_profile: @user_profile

br

div
  =< link_to "Back to profile", user_profile_path

app/views/user/profiles/index.html.slim
p style="color: green" = notice

h1 Profiles

#user_profiles
  - @user_profiles.each do |user_profile|
    == render user_profile
    p
      = link_to "Show this profile", user_profile

= link_to "New profile", new_user_profile_path

app/views/user/profiles/new.html.slim
h1 New profile

== render "form", user_profile: @user_profile

br

div
  = link_to "Back to profiles", user_profiles_path

app/views/user/profiles/show.html.slim
.w-full
  .mx-auto
    == render @user_profile

    div.mt-4
      => link_to "Edit this profile", user_profile_edit_path, class: 'my-2 bg-blue-500 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded'