config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'
  get 'home/index', to: 'home#index'

  namespace :user do
    get 'profile', to: 'profiles#show'
    get 'profile/edit', to: 'profiles#edit'
    put 'profile', to: 'profiles#update'
  end

  devise_scope :user do
    get :users, to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :clubs
  resources :rounds
  resources :players
  resources :tournaments do
    resources :matches do
      member do
        post :add_goal # should be MatchGoal nested resource?
      end
    end
    resources :teams do
      collection do
        get :register
        post :create_from_register
      end

      member do
        get :registration_done
      end
    end
  end
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
  include CountryNameable

  has_many :tournament_team_players, inverse_of: :tournament, dependent: :destroy
  has_many :tournament_teams, through: :tournament_team_players, source: :team
  has_many :teams, inverse_of: :tournament, dependent: :nullify
  has_many :rounds, inverse_of: :tournament, dependent: :destroy
  has_many :matches, through: :rounds, source: :matches

  accepts_nested_attributes_for :tournament_team_players, allow_destroy: true, reject_if: :all_blank
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[show edit update destroy]

  # GET /tournaments or /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1 or /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments or /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournament_url(@tournament), notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1 or /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_url(@tournament), notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1 or /tournaments/1.json
  def destroy
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tournament_params
    params.require(:tournament).permit(:name, :description, :starts_at, :ends_at, :address, :city, :country_code,
                                       :latitude, :longitude)
  end
end

app/helpers/tournaments_helper.rb
# frozen_string_literal: true

module TournamentsHelper
end

app/views/tournaments/_form.html.slim
= form_with(model: tournament, class: "contents") do |form|
  - if tournament.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      h2
        = pluralize(tournament.errors.count, "error")
        |  prohibited this tournament from being saved:
      ul
        - tournament.errors.each do |error|
          li
            = error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :description
    = form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :starts_at
    = form.datetime_field :starts_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :ends_at
    = form.datetime_field :ends_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :address
    = form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :city
    = form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :country_code
    = form.country_select :country_code, {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :latitude
    = form.text_field :latitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :longitude
    = form.text_field :longitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/tournaments/_teams_list.html.slim
div[class="overflow-x-auto relative shadow-md sm:rounded-lg"]
  table[class="w-full text-sm text-left text-gray-500 dark:text-gray-400"]
    thead[class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"]
      tr
          th[scope="col" class="py-3 px-6"]
            = Team.human_attribute_name(:name)
          th[scope="col" class="py-3 px-6"]
            = Team.human_attribute_name(:players)
          /th[scope="col" class="py-3 px-6"]
            | Category
          /th[scope="col" class="py-3 px-6"]
            | Price
          /th[scope="col" class="py-3 px-6"]
            | Action
    tbody
      - teams.each_with_index do |team, index|
        tr[class="#{index.even? ? 'bg-white dark:bg-gray-900': 'bg-gray-50 dark: bg-gray-800'} border-b dark:border-gray-700"]
          th[ scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"]
            = link_to team.name, tournament_team_path(tournament_id: @tournament.id, id: team.id)
          td[class="py-4 px-6"]
            = team.players_display_names
          /td[class="py-4 px-6"]
            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>

app/views/tournaments/_tournament.html.slim
| <div id="
= dom_id tournament
| "> 
p.my-5
  strong.block.font-medium.mb-1
    | Name:
  = tournament.name
p.my-5
  strong.block.font-medium.mb-1
    | Description:
  = tournament.description
p.my-5
  strong.block.font-medium.mb-1
    | Starts at:
  = tournament.starts_at
p.my-5
  strong.block.font-medium.mb-1
    | Ends at:
  = tournament.ends_at
p.my-5
  strong.block.font-medium.mb-1
    | Address:
  = tournament.address
p.my-5
  strong.block.font-medium.mb-1
    | City:
  = tournament.city
p.my-5
  strong.block.font-medium.mb-1
    | Country:
  => tournament.country_flag
  = tournament.country_name
  |  (
  = tournament.country_code
  |)
p.my-5
  strong.block.font-medium.mb-1
    | Latitude:
  = tournament.latitude
p.my-5
  strong.block.font-medium.mb-1
    | Longitude:
  = tournament.longitude

h3.font-medium.text-xl
  = Team.model_name.human(count: 2)
ol.list-decimal
  - tournament.teams.each do |team|
    li
      = link_to team.name, tournament_team_path(tournament_id: tournament.id, id: team.id)
      =< team.tournament_team_players.map(&:player).flat_map(&:country_flag).uniq.join('')
  - if tournament.teams.any?
    = render 'tournaments/teams_list', teams: tournament.teams, tournament: tournament
  - else
    = t('teams.empty', default: 'No teams for this tournament')
- if action_name != "show"
  = link_to "Show this tournament", tournament, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to 'Edit this tournament', edit_tournament_path(tournament), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  hr.mt-6

app/views/tournaments/edit.html.slim
.w-full
  h1.font-bold.text-4xl
    = t('editing')
    =< Tournament.model_name.human
  = render "form", tournament: @tournament
  = link_to "Show this tournament", @tournament, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to tournaments", tournaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/tournaments/index.html.slim
.w-full
  / - if notice.present?
  /   p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
  /     = notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      = Tournament.model_name.human(count: 2)
    = link_to "#{t('new')} #{Tournament.model_name.human.downcase}", new_tournament_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #tournaments.min-w-full
    /= render @tournaments
    = render TournamentComponent.with_collection(@tournaments)

app/views/tournaments/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    = t('new')
    =< Tournament.model_name.human
  = render "form", tournament: @tournament
  = link_to 'Back to tournaments', tournaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/tournaments/show.html.slim
.w-full
  .mx-auto
    / - if notice.present?
    /   p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
    /     = notice
    = render @tournament
    = link_to 'Edit this tournament', edit_tournament_path(@tournament), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to 'Destroy this tournament', tournament_path(@tournament), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to 'Back to tournaments', tournaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to 'Register', register_tournament_teams_path(@tournament), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"