config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'
  get 'home/index', to: 'home#index'

  namespace :user do
    get 'profile', to: 'profiles#show'
    get 'profile/edit', to: 'profiles#edit'
    put 'profile', to: 'profiles#update'
  end

  devise_scope :user do
    get :users, to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :clubs
  resources :rounds
  resources :players
  resources :tournaments do
    resources :matches do
      member do
        post :add_goal # should be MatchGoal nested resource?
      end
    end
    resources :teams do
      collection do
        get :register
        post :create_from_register
      end

      member do
        get :registration_done
      end
    end
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  has_many :tournament_team_players, inverse_of: :player, dependent: :destroy

  belongs_to :profile, inverse_of: :player

  accepts_nested_attributes_for :profile

  # delegate national flag to profile
  delegate :country_flag, to: :profile, allow_nil: true
  delegate :gender, to: :profile, allow_nil: true
  delegate :name, to: :profile, prefix: true, allow_nil: true

  def national_flag
    country_flag
  end

  def name
    profile_name || super
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:name, :nickname)
  end
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/views/players/_form.html.slim
= form_with(model: @player) do |form|
  - if @player.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@player.errors.count, 'error')} prohibited this player from being saved:"
      ul
        - @player.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :nickname, style: "display: block"
    = form.text_field :nickname

  div
    = form.submit

app/views/players/_player.html.slim
div id="#{dom_id player}"
  p
    strong Name:
    =< player.name
  p
    strong Nickname:
    =< player.nickname

app/views/players/edit.html.slim
h1 Editing player

== render "form", player: @player

br

div
  => link_to "Show this player", @player
  '|
  =< link_to "Back to players", players_path

app/views/players/index.html.slim
p style="color: green" = notice

h1 Players

#players
  - @players.each do |player|
    == render player
    p
      = link_to "Show this player", player

= link_to "New player", new_player_path

app/views/players/new.html.slim
h1 New player

== render "form", player: @player

br

div
  = link_to "Back to players", players_path

app/views/players/show.html.slim
p style="color: green" = notice

== render @player

div
  => link_to "Edit this player", edit_player_path(@player)
  '|
  =< link_to "Back to players", players_path

  = button_to "Destroy this player", @player, method: :delete