config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'
  get 'home/index', to: 'home#index'

  namespace :user do
    get 'profile', to: 'profiles#show'
    get 'profile/edit', to: 'profiles#edit'
    put 'profile', to: 'profiles#update'
  end

  devise_scope :user do
    get :users, to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :clubs
  resources :rounds
  resources :players
  resources :tournaments do
    resources :matches do
      member do
        post :add_goal # should be MatchGoal nested resource?
      end
    end
    resources :teams do
      collection do
        get :register
        post :create_from_register
      end

      member do
        get :registration_done
      end
    end
  end
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  belongs_to :round
  has_one :tournament, through: :round
  belongs_to :home_team, class_name: 'Team'
  belongs_to :visitor_team, class_name: 'Team'

  has_many :match_goals, inverse_of: :match, dependent: :destroy
  has_many :match_fouls, inverse_of: :match, dependent: :destroy

  delegate :name, to: :round, prefix: true
  delegate :name, to: :home_team, prefix: true
  delegate :name, to: :visitor_team, prefix: true

  def add_home_goal(player: nil, time: nil, own_goal: false)
    add_goal(team: home_team, player: player, time: time, own_goal: own_goal)
  end

  def add_visitor_goal(player: nil, time: nil, own_goal: false)
    add_goal(team: visitor_team, player: player, time: time, own_goal: own_goal)
  end

  def add_goal(team:, player: nil, time: nil, own_goal: false)
    match_goals.create(
      tournament_team_player: tournament_team_player(team:, player:),
      time: time,
      own_goal: own_goal
    )
  end

  def substract_home_goal
    # pending. Maybe non-sense because I need to know which goal to remove, and
    # I can know the goal by ID, so just destroy the goal record by ID.
  end

  def substract_visitor_goal
    # pending. Maybe non-sense because I need to know which goal to remove, and
    # I can know the goal by ID, so just destroy the goal record by ID.
  end

  def substract_goal
    # pending. Maybe non-sense because I need to know which goal to remove, and
    # I can know the goal by ID, so just destroy the goal record by ID.
  end

  def tournament_team_player(team:, player:)
    TournamentTeamPlayer.find_by(
      team:,
      player:,
      tournament: # get this with belongs_to through?
    )
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :set_tournament,
                only: %i[index show new create edit update destroy add_goal]
  before_action :set_match, only: %i[show edit update destroy add_goal]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to tournament_match_url(@tournament, @match), notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to tournament_match_url(@tournament, @match), notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_goal
    # debugger
    tournament_team_player = TournamentTeamPlayer.find(
      params['tournament_team_player_id']
    )
    @match.add_goal(
      team: tournament_team_player.team,
      player: tournament_team_player.player
    )
    # debugger
    render json: @match, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tournament
    @tournament = Tournament.includes(:rounds, :teams).find(params[:tournament_id])
  end

  def set_match
    @match = @tournament.matches.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def match_params
    params.require(:match).permit(:round_id, :home_team_id, :visitor_team_id, :home_score, :visitor_score)
  end
end

app/helpers/matches_helper.rb
# frozen_string_literal: true

module MatchesHelper
end

app/views/matches/_edit_form.html.slim
= form_with(model: match, url: [tournament, match], class: 'contents') do |form|
  - if match.errors.any?
    div style="color: red"
      h2 = "#{pluralize(match.errors.count, 'error')} prohibited this match from being saved:"
      ul
        - match.errors.each do |error|
          li = error.full_message

  h2
    = match.round.name

  h3
    = Match.human_attribute_name(:home_team)
    |:
    =<> match.home_team_name
    | vs
    =< Match.human_attribute_name(:visitor_team)
    |:
    =< match.visitor_team_name

  br

  .results
    .teams.md:grid.grid-cols-11.gap-4
      .home_team.col-span-5
        .score
          = t('score')
          |:
          span.value
            =< match.home_score || 0
        == render "team_players", team: match.home_team, match: match
      .separator vs.
      .visitor_team.col-span-5
        .score
          = t('score')
          |:
          span.value
            =< match.visitor_score || 0
        == render "team_players", team: match.visitor_team, match: match
        / .name = match.visitor_team_name
  div
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/matches/_form.html.slim
= form_with(model: match, url: [tournament, match], class: 'contents') do |form|
  - if match.errors.any?
    div style="color: red"
      h2 = "#{pluralize(match.errors.count, 'error')} prohibited this match from being saved:"
      ul
        - match.errors.each do |error|
          li = error.full_message

  div
    = form.label :round_id, style: "display: block"
    = form.collection_select :round_id, tournament.rounds, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.label :home_team_id, style: "display: block"
    = form.collection_select :home_team_id, tournament.teams, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.label :visitor_team_id, style: "display: block"
    = form.collection_select :visitor_team_id, tournament.teams, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/matches/_match.html.slim
div id="#{dom_id match}"
  p
    strong Round:
    =< match.round_name
  p
    strong Home team:
    =< match.home_team_name
  p
    strong Visitor team:
    =< match.visitor_team_name
  p
    strong Home score:
    =< match.home_score
  p
    strong Visitor score:
    =< match.visitor_score

app/views/matches/_new_form.html.slim
= form_with(model: match, url: [tournament, match], class: 'contents') do |form|
  - if match.errors.any?
    div style="color: red"
      h2 = "#{pluralize(match.errors.count, 'error')} prohibited this match from being saved:"
      ul
        - match.errors.each do |error|
          li = error.full_message

  div
    = form.label :round_id, style: "display: block"
    = form.collection_select :round_id, tournament.rounds, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.label :home_team_id, style: "display: block"
    = form.collection_select :home_team_id, tournament.teams, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.label :visitor_team_id, style: "display: block"
    = form.collection_select :visitor_team_id, tournament.teams, :id, :name, { prompt: true }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  div
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/matches/_team_players.html.slim
.title
  .name = team.name
  / .score = match.home_score
.players[data-controller='matches']
  ul
    - team.tournament_team_players.each do |ttplayer|
      li
        = ttplayer.player.name
        button [
          data-action="matches#addGoal"
          data-matches-tournament-team-player-id-param="#{ttplayer.id}"
          data-matches-tournament-id-param="#{match.tournament.id}"
          data-matches-match-id-param="#{match.id}"
          class="px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        ]
          =< t("match.goal.add", default: "add goal")

app/views/matches/edit.html.slim
.w-full

  h1 Editing match

  == render "edit_form", match: @match, tournament: @tournament

  br

  div
    => link_to "Show this match", tournament_match_path(@tournament, @match)
    '|
    =< link_to "Back to matches", tournament_matches_path

app/views/matches/index.html.slim
.w-full
  p style="color: green" = notice

  h1 Matches

  #matches
    - if @matches.empty?
      p = t('matches.empty', default: 'No matches')
    - else
      - @matches.each do |match|
        == render match
        p
          = link_to "Show this match", tournament_match_path(match.tournament, match)

  = link_to "New match", new_tournament_match_path(@tournament)

app/views/matches/new.html.slim
.w-full
  h1 New match

  == render "new_form", match: @match, tournament: @tournament

  br

  div
    = link_to "Back to matches", tournament_matches_path(@tournament)

app/views/matches/show.html.slim
.w-full
  p style="color: green" = notice

  == render @match

  div
    => link_to "Edit this match", edit_tournament_match_path(@tournament, @match)
    '|
    =< link_to "Back to matches", tournament_matches_path

    = button_to "Destroy this match", tournament_match_path(@tournament, @match), method: :delete